### ISSUE TITLE
linkazza - wbr removal also removes normal text

### ISSUE THREAD

**Issue by hurda** [meh/userscripts#1]
Hello!

I found your userscript while searching for a linkification-script without Mutation Events, and it worked great. Until I found a site which extensively used wbrs. On that site, using linkazza lead to weird results.

Then I saw that somebody already reported this error over at userscript.org with a test-site:
http://userscripts.org/topics/127831

In the JSFiddle, linkazza is removing all the wbr-tags and all characters after the first <span> which aren't placed into <spans>.

The following script is an example for proper removal of the wbrs:
http://userscripts.org/scripts/show/160675
It's basically the original "Linkify Plus" with wbr-removal.

**Comment by meh** [comment]
Thanks, for some reason I didn't get a notification about the message on userscripts.org.

The example removes all WBRs, what I try to do is remove them to parse the link and then add them back in the proper place inside the `<a>` tag, which is a bit harder :P

Now that I have a decent example that completely fucks up I'll try to fix it.
